2019-01-13 04:40:46,532 INFO: Microblog startup [in C:\microblog\app\__init__.py:44]
2019-01-13 04:41:43,673 INFO: Microblog startup [in C:\microblog\app\__init__.py:44]
2019-01-13 04:48:23,001 INFO: Microblog startup [in C:\microblog\app\__init__.py:44]
2019-01-14 03:40:15,110 INFO: Microblog startup [in C:\microblog\app\__init__.py:44]
2019-01-14 03:40:53,425 ERROR: Exception on /explore [GET] [in c:\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\microblog\app\routes.py", line 136, in explore
    return render_template('index.html', title = 'Explore', posts = posts)
  File "c:\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\microblog\app\templates\index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "C:\microblog\app\templates\base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "C:\microblog\app\templates\index.html", line 21, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2019-01-14 03:41:23,592 INFO: Microblog startup [in C:\microblog\app\__init__.py:44]
2019-01-14 04:17:41,193 INFO: Microblog startup [in C:\microblog\app\__init__.py:44]
2019-01-14 04:30:01,264 INFO: Microblog startup [in C:\microblog\app\__init__.py:44]
2019-01-14 04:30:08,622 ERROR: Exception on /user/dwarkanath [GET] [in c:\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\microblog\app\routes.py", line 78, in user
    posts = user.posts.order_by(Post.datetime.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
AttributeError: type object 'Post' has no attribute 'datetime'
2019-01-14 04:30:52,718 INFO: Microblog startup [in C:\microblog\app\__init__.py:44]
2019-01-14 04:32:12,311 INFO: Microblog startup [in C:\microblog\app\__init__.py:44]
2019-01-14 04:32:50,609 INFO: Microblog startup [in C:\microblog\app\__init__.py:44]
